version: '3.9'

services:
  redis:
    image: redis:latest

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    image: api:1.0
    volumes:
      - ./api/src:/app/api/src
      - ./api/package.json:/app/api/package.json

  app:
    stdin_open: true
    depends_on:
      - worker
    build:
      dockerfile: Dockerfile
      context: ./calc
    image: calc:1.0
    volumes:
      - ./calc/src:/app/calc/src
      - ./calc/package.json:/app/calc/package.json
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_TOKEN=abcdefgh12345678

  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    image: worker:1.0
    volumes:
      - ./worker/src:/app/worker/src
      - ./worker/package.json:/app/worker/package.json

  nginx:
    depends_on:
      - app
      - api
      - worker
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: mi-nginx:1.0
    ports:
      - "4000:80"

